In [1]:
import pandas as pd

# Read the data

In [2]:
filepath = '../Data/shopping_dataset.xlsx'
df = pd.read_excel(filepath, nrows=52924, sheet_name='in')
df = df.iloc[:,1:] # get rid of the first column (row number)

pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
df.tail()

,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status,GST,Date,Offline_Spend,Online_Spend,Month,Coupon_Code,Discount_pct
52919,13155,F,California,8,22504,2019-03-10,GGOEGGCX056399,Gift Card - $250.00,Gift Cards,1,250.00,0.0,Clicked,0.05,2019-03-10,2500,1294.22,3,GC30,30.0
52920,18077,M,Chicago,34,24250,2019-03-28,GGOEGGCX056299,Gift Card - $25.00,Gift Cards,1,25.00,0.0,Used,0.05,2019-03-28,2000,1066.12,3,GC30,30.0
52921,16085,M,California,15,39991,2019-10-06,GGOEGOCD078399,Google Leather Perforated Journal,Notebooks & Journals,1,10.80,6.0,Clicked,0.05,2019-10-06,3000,2230.76,10,NJ10,10.0
52922,16085,M,California,15,39991,2019-10-06,GGOEGOCR078499,Google Spiral Leather Journal,Notebooks & Journals,1,9.60,6.0,Used,0.05,2019-10-06,3000,2230.76,10,NJ10,10.0
52923,13659,F,Chicago,8,39998,2019-10-06,GGOEGOCC077999,Google Spiral Journal with Pen,Notebooks & Journals,1,5.59,6.5,Not Used,0.05,2019-10-06,3000,2230.76,10,NJ10,10.0

# Get the relevant columns only

In [3]:
df = df[['CustomerID', 'Transaction_Date', 'Product_SKU', 'Product_Description']]
df.head()

,CustomerID,Transaction_Date,Product_SKU,Product_Description
0,17850,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...
1,17850,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...
2,17850,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA
3,17850,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA
4,17850,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...

# Get the reference file for the products

In [4]:
df_ref = pd.read_csv('../Data/prod_categories.csv')
df_ref.head()

,Product_Description,Product_Category,Predicted_Category
0,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,home & kitchen
1,Nest Cam Outdoor Security Camera - USA,Nest-USA,home & kitchen
2,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,home & kitchen
3,Nest Cam Indoor Security Camera - USA,Nest-USA,home & kitchen
4,Nest Protect Smoke + CO White Wired Alarm-USA,Nest-USA,home & kitchen

# Joining the predicted_category to the shopping dataset

In [5]:
df = pd.merge(df, df_ref
             ,how='left'
             ,left_on='Product_Description'
             ,right_on='Product_Description')
df = df.drop(columns=['Product_Category'])
df.head()

,CustomerID,Transaction_Date,Product_SKU,Product_Description,Predicted_Category
0,17850,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,home & kitchen
1,17850,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,home & kitchen
2,17850,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,home & kitchen
3,17850,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,home & kitchen
4,17850,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,home & kitchen

# We store the features in a parquet file (much faster than CSV)

In [6]:
df_features = pd.pivot_table(df[['CustomerID', 'Predicted_Category']]
                               ,index='CustomerID'
                               ,columns = 'Predicted_Category'
                               ,aggfunc='size'
                               ,fill_value=0)
df_features.to_parquet('../Data/features.parquet.gz', compression='gzip')